# Automatically generated by TopicTreeSpecPrinter(**kwargs).
# The kwargs were:
# - fileObj: TextIOWrapper
# - footer: '# End of topic tree definition. Note that application may l...'
# - indentStep: 4
# - treeDoc: None
# - width: 70


class engine:
    """
    Superclass for all messages emitted by the engine
    """
    class answer:
        """
        Class for all answers to requests from the GUI
        """
        class process_variable:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(pv):
                """
                - pv: float
                """
        class working_output:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(output):
                """
                - output: UNDOCUMENTED
                """
        class working_setpoint:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(setpoint):
                """
                - setpoint: UNDOCUMENTED
                """
        class sensor_value:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(value):
                """
                - value: UNDOCUMENTED
                """
        class pid:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(p, i, d):
                """
                - p: UNDOCUMENTED
                - i: UNDOCUMENTED
                - d: UNDOCUMENTED
                """
    class status:
        """
        Class for all status messages emitted by the engine
        """
        def msgDataSpec(text):
            """
            - text: UNDOCUMENTED
            """

class gui:
    """
    Superclass for all messages emitted by the GUI
    """
    class con:
        """
        UNDOCUMENTED: created as parent without specification
        """
        class connect_controller:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(controller_type, controller_port):
                """
                - controller_type: UNDOCUMENTED
                - controller_port: UNDOCUMENTED
                """
        class connect_sensor:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(sensor_type, sensor_port):
                """
                - sensor_port: UNDOCUMENTED
                - sensor_type: UNDOCUMENTED
                """
        class disconnect_controller:
            """
            UNDOCUMENTED: created without spec
            """

        class disconnect_sensor:
            """
            UNDOCUMENTED: created without spec
            """

    class set:
        """
        UNDOCUMENTED: Class for all set command from the GUI (i.e. unidirectional commands wirthout expected repsonse)
        """
        class automatic_mode:
            """
            UNDOCUMENTED: created without spec
            """
        class manual_mode:
            """
            UNDOCUMENTED: created without spec
            """
        class manual_power:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(power):
                """
                - power: UNDOCUMENTED
                """
        class rate:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(rate):
                """
                - rate: UNDOCUMENTED
                """
        class target_setpoint:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(setpoint):
                """
                - setpoint: UNDOCUMENTED
                """
        class pid_p:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(p):
                """
                - p: UNDOCUMENTED
                """
        class pid_i:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(i):
                """
                - i: UNDOCUMENTED
                """
        class pid_d:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(d):
                """
                - d: UNDOCUMENTED
                """

    class request:
        """
        Class for all requests from the GUI, i.e. an answer is expected
        """
        class process_variable:
            """
            UNDOCUMENTED: created without spec
            """
        class working_output:
            """
            UNDOCUMENTED: created without spec
            """
        class working_setpoint:
            """
            UNDOCUMENTED: created without spec
            """
        class sensor_value:
            """
            UNDOCUMENTED: created without spec
            """
        class pid:
            """
            UNDOCUMENTED: created without spec
            """

    class log:
        """
        A class for everthing related to the logging module
        """
        class start:
            """
            UNDOCUMENTED: created without spec
            """
        class stop:
            """
            UNDOCUMENTED: created without spec
            """
        class cont:
            """
            UNDOCUMENTED: created without spec
            """
        class filename:
            """
            UNDOCUMENTED: created without spec
            """
            def msgDataSpec(filename):
                """
                - filename: UNDOCUMENTED
                """
# End of topic tree definition. Note that application may load
# more than one definitions provider.
