import enum
from _typeshed import Incomplete

import serial

__url__: str
__version__: str
MODE_RTU: str
MODE_ASCII: str
BYTEORDER_BIG: int
BYTEORDER_LITTLE: int
BYTEORDER_BIG_SWAP: int
BYTEORDER_LITTLE_SWAP: int


class _Payloadformat(enum.Enum):
    BIT = ...
    BITS = ...
    FLOAT = ...
    LONG = ...
    REGISTER = ...
    REGISTERS = ...
    STRING = ...


class Instrument:
    address: Incomplete
    mode: Incomplete
    precalculate_read_size: bool
    debug: Incomplete
    clear_buffers_before_each_transaction: bool
    close_port_after_each_call: Incomplete
    handle_local_echo: bool
    serial: serial.Serial | None

    def __init__(self, port: str | serial.Serial, slaveaddress: int, mode: str = ...,
                 close_port_after_each_call: bool = False, debug: bool = False) -> None: ...

    @property
    def roundtrip_time(self) -> float | None: ...

    def read_bit(self, registeraddress: int, functioncode: int = 2) -> int: ...

    def write_bit(self, registeraddress: int, value: int, functioncode: int = 5) -> None: ...

    def read_bits(self, registeraddress: int, number_of_bits: int, functioncode: int = 2) -> list[int]: ...

    def write_bits(self, registeraddress: int, values: list[int]) -> None: ...

    def read_register(self, registeraddress: int, number_of_decimals: int = 0, functioncode: int = 3,
                      signed: bool = False) -> int | float: ...

    def write_register(self, registeraddress: int, value: int | float, number_of_decimals: int = 0,
                       functioncode: int = 16, signed: bool = False) -> None: ...

    def read_long(self, registeraddress: int, functioncode: int = 3, signed: bool = False, byteorder: int = ...,
                  number_of_registers: int = 2) -> int: ...

    def write_long(self, registeraddress: int, value: int, signed: bool = False, byteorder: int = ...,
                   number_of_registers: int = 2) -> None: ...

    def read_float(self, registeraddress: int, functioncode: int = 3, number_of_registers: int = 2,
                   byteorder: int = ...) -> float: ...

    def write_float(self, registeraddress: int, value: int | float, number_of_registers: int = 2,
                    byteorder: int = ...) -> None: ...

    def read_string(self, registeraddress: int, number_of_registers: int = 16, functioncode: int = 3) -> str: ...

    def write_string(self, registeraddress: int, textstring: str, number_of_registers: int = 16) -> None: ...

    def read_registers(self, registeraddress: int, number_of_registers: int, functioncode: int = 3) -> list[int]: ...

    def write_registers(self, registeraddress: int, values: list[int]) -> None: ...


class ModbusException(IOError): ...


class SlaveReportedException(ModbusException): ...


class SlaveDeviceBusyError(SlaveReportedException): ...


class NegativeAcknowledgeError(SlaveReportedException): ...


class IllegalRequestError(SlaveReportedException): ...


class MasterReportedException(ModbusException): ...


class NoResponseError(MasterReportedException): ...


class LocalEchoError(MasterReportedException): ...


class InvalidResponseError(MasterReportedException): ...
